### ISSUE TITLE
Infinite spinny icon if no games uploaded

### ISSUE THREAD

**Issue by hryx** [gotosleep/ItchDroid#1]
I haven't uploaded any games to my Itch.io account. After logging in to the Android app, I get the spinning "loading" animation forever.

It's not super informative; a "you have no games" screen or something similar might be more helpful.

**Comment by leafo** [comment]
+1

**Comment by kgs0142** [comment]
Oh...so this is the reason, I have the same issue here.

**Comment by Turupawn** [comment]
I fixed this (and some other stuff) on this PR:
https://github.com/gotosleep/ItchDroid/pull/2

@gotosleep What do you think?

**Comment by gotosleep** [comment]
@Turupawn looks good, thanks!
